### ISSUE TITLE
Web site examples / doc not updating

### ISSUE THREAD

**Issue by jourdain** [Kitware/vtk-js#1771]
```
Error: ENOENT: no such file or directory, open '/home/runner/work/vtk-js/vtk-js/Documentation/build-tmp/public/examples/WidgetRepresentation/WidgetRepresentation.js'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at bundleIntoSingleHtml (/home/runner/work/vtk-js/vtk-js/node_modules/kw-doc/bin/examples.js:276:21)
    at bundleExamples (/home/runner/work/vtk-js/vtk-js/node_modules/kw-doc/bin/examples.js:364:7)
    at /home/runner/work/vtk-js/vtk-js/node_modules/kw-doc/bin/examples.js:381:9
    at tryCatcher (/home/runner/work/vtk-js/vtk-js/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.errorAdapter [as _rejectionHandler0] (/home/runner/work/vtk-js/vtk-js/node_modules/bluebird/js/release/nodeify.js:35:34)
    at Promise._settlePromise (/home/runner/work/vtk-js/vtk-js/node_modules/bluebird/js/release/promise.js:601:21)
    at Promise._settlePromise0 (/home/runner/work/vtk-js/vtk-js/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/runner/work/vtk-js/vtk-js/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/runner/work/vtk-js/vtk-js/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/runner/work/vtk-js/vtk-js/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/runner/work/vtk-js/vtk-js/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/home/runner/work/vtk-js/vtk-js/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/runner/work/vtk-js/vtk-js/Documentation/build-tmp/public/examples/WidgetRepresentation/WidgetRepresentation.js'
}
```

@finetjul

**Comment by jourdain** [comment]
https://github.com/Kitware/vtk-js/runs/2068430014?check_suite_focus=true

**Comment by finetjul** [comment]
Documentation does not build on Windows.
Nonetheless, I think I know why it fails: [CubeHandleRepresentation](https://github.com/Kitware/vtk-js/blob/master/Sources/Widgets/Representations/WidgetRepresentation/example/index.js#L3) no longer exists. @ocrossi any reason why it has been removed when adding the arrow/line widget ?

Could building/running the examples be a "test" in the test run suite to catch those example failures?
