### ISSUE TITLE
Regression dragging mouse

### ISSUE THREAD

**Issue by MayeulChassagnard** [Kitware/vtk-js#214]
As noticed in the MR https://github.com/girder/girder/pull/1951, the latest vtk-js version faces a regression when dragging the mouse over a dicom image with the dicom_viewer plugin in girder.

We get the following error:

```
Uncaught TypeError: publicAPI.superHandleMouseMove is not a function
    at Object.publicAPI.handleAnimation (http://localhost:8080/static/built/plugins/dicom_viewer/plugin.min.js:38098:15)
    at Object.<anonymous> (http://localhost:8080/static/built/plugins/dicom_viewer/plugin.min.js:39450:44)
    at http://localhost:8080/static/built/plugins/dicom_viewer/plugin.min.js:2555:35
    at Array.forEach (native)
    at Object.publicAPI.(anonymous function) [as invokeAnimation] (http://localhost:8080/static/built/plugins/dicom_viewer/plugin.min.js:2554:15)
    at Object.publicAPI.animationEvent (http://localhost:8080/static/built/plugins/dicom_viewer/plugin.min.js:40709:17)
    at publicAPI.handleAnimation (http://localhost:8080/static/built/plugins/dicom_viewer/plugin.min.js:40541:15)
publicAPI.handleAnimation @ index.js:83
(anonymous) @ index.js:81
(anonymous) @ macro.js:577
publicAPI.(anonymous function) @ macro.js:577
publicAPI.animationEvent @ index.js:424
publicAPI.handleAnimation @ index.js:255
```

**Comment by martinken** [comment]
Fixed in https://github.com/Kitware/vtk-js/pull/215
