### ISSUE TITLE
Example build failure on Node 17 on Windows

### ISSUE THREAD

**Issue by tbirdso** [Kitware/vtk-js#2141]
### High-level description

Examples are failing to build with Node v17.0.1 by default. The issue is highlighted [here](https://github.com/webpack/webpack/issues/14532) as a problem in Webpack. A temporary workaround updating the build command is proposed [here](https://stackoverflow.com/questions/69665222/node-17-0-1-causes-some-error-digital-envelope-routinesunsupported).

### Steps to reproduce

`npm run example -- GeometryViewer`

### Detailed behavior

Default output:
```
<s> [webpack.Progress] 10% building 0/2 entries 2/2 dependencies 0/2 modules
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (C:\repos\vtk-js\node_modules\webpack\lib\util\createHash.js:145:18)
    at BulkUpdateDecorator.update (C:\repos\vtk-js\node_modules\webpack\lib\util\createHash.js:46:50)
    at OriginalSource.updateHash (C:\repos\vtk-js\node_modules\webpack-sources\lib\OriginalSource.js:131:8)
    at NormalModule._initBuildHash (C:\repos\vtk-js\node_modules\webpack\lib\NormalModule.js:888:17)
    at handleParseResult (C:\repos\vtk-js\node_modules\webpack\lib\NormalModule.js:954:10)
    at C:\repos\vtk-js\node_modules\webpack\lib\NormalModule.js:1048:4
    at processResult (C:\repos\vtk-js\node_modules\webpack\lib\NormalModule.js:763:11)
    at C:\repos\vtk-js\node_modules\webpack\lib\NormalModule.js:827:5
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (C:\repos\vtk-js\node_modules\webpack\lib\util\createHash.js:145:18)
    at BulkUpdateDecorator.update (C:\repos\vtk-js\node_modules\webpack\lib\util\createHash.js:46:50)
    at SourceMapSource.updateHash (C:\repos\vtk-js\node_modules\webpack-sources\lib\SourceMapSource.js:231:8)
    at NormalModule._initBuildHash (C:\repos\vtk-js\node_modules\webpack\lib\NormalModule.js:888:17)
    at handleParseResult (C:\repos\vtk-js\node_modules\webpack\lib\NormalModule.js:954:10)
    at C:\repos\vtk-js\node_modules\webpack\lib\NormalModule.js:1048:4
    at processResult (C:\repos\vtk-js\node_modules\webpack\lib\NormalModule.js:763:11)
    at C:\repos\vtk-js\node_modules\webpack\lib\NormalModule.js:827:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

As discussed in the [Webpack thread](https://github.com/webpack/webpack/issues/14532) the user can manually set the NODE_OPTIONS variable with `export NODE_OPTIONS=--openssl-legacy-provider` (bash) or `SET NODE_OPTIONS=--openssl-legacy-provider` (batch) to circumvent this issue.

### Expected behavior

Example builds successfully

### Environment
- **vtk.js**: v20.2.1
- **OS**: Windows, Linux
- Node.js v17.0.1

**Comment by daker** [comment]
@tbirdso not relevant anymore, node 22 is the version used to run the build and test

**Comment by tbirdso** [comment]
Thanks, closing as stale.
