### ISSUE TITLE
Uncaught TypeError: t.lastRenderPassShaderReplacement is not a function after fix #2344

### ISSUE THREAD

**Issue by cnszpeak** [Kitware/vtk-js#2349]
vtk.js:2 
 Uncaught TypeError: t.lastRenderPassShaderReplacement is not a function
    at Object.HG.e.buildShaders (vtk.js:2:1268034)
    at Object.HG.e.updateShaders (vtk.js:2:1287074)
    at Object.HG.e.renderPieceDraw (vtk.js:2:1295332)
    at Object.HG.e.renderPiece (vtk.js:2:1296396)
    at Object.HG.e.render (vtk.js:2:1267921)
    at HG.e.translucentPass (vtk.js:2:1267504)
    at Object.LR.e.apply (vtk.js:2:1017231)
    at Object.LR.e.traverse (vtk.js:2:1017090)
    at e.traverseTranslucentPass (vtk.js:2:1254184)
    at Object.LR.e.traverse (vtk.js:2:1017078)
HG.e.buildShaders	@	vtk.js:2
HG.e.updateShaders	@	vtk.js:2
HG.e.renderPieceDraw	@	vtk.js:2
HG.e.renderPiece	@	vtk.js:2
HG.e.render	@	vtk.js:2
HG.e.translucentPass	@	vtk.js:2
LR.e.apply	@	vtk.js:2
LR.e.traverse	@	vtk.js:2
e.traverseTranslucentPass	@	vtk.js:2
LR.e.traverse	@	vtk.js:2
LR.e.traverse	@	vtk.js:2
e.traverse	@	vtk.js:2
e.traverse	@	vtk.js:2
YF.e.traverseAllPasses	@	vtk.js:2
c	@	vtk.js:2
e.render	@	vtk.js:2
TS.e.updateViewport	@	vtk.js:2
(匿名)	@	vtk.js:2
e.modified	@	vtk.js:2
TS.e.setEnabled	@	vtk.js:2

**Comment by zishiwu123** [comment]
Hi @cnszpeak , thank you for reporting this bug. Can you please follow the bug report template? It will make it easier for maintainers to figure out the cause of this bug: https://github.com/Kitware/vtk-js/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

For an example bug report, see issue #2257.

**Comment by martinken** [comment]
@zishiwu123 did my latest merge fix it for you? I worked for me locally but I can only fake webgl1.
