### ISSUE TITLE
TypeError in ImageMapper

### ISSUE THREAD

**Issue by jilei-hao** [Kitware/vtk-js#2710]
### High-level description

When user keep scrolling to change the slice of an image, type error was thrown in the console and renderer stopped rendering. 
### Steps to reproduce

- Open https://kitware.github.io/vtk-js/examples/ImageMapper/index.html
- Keep scrolling for a while and the error will occur
### Detailed behavior

Error message: 

ImageMapper.js:1 Uncaught TypeError: Failed to execute 'bindTexture' on 'WebGL2RenderingContext': parameter 2 is not of type 'WebGLTexture'.
    at e.bind (ImageMapper.js:1:89660)
    at e.activate (ImageMapper.js:1:89176)
    at Or.e.renderPieceDraw (ImageMapper.js:1:120724)
    at Or.e.renderPiece (ImageMapper.js:1:121266)
    at Or.e.render (ImageMapper.js:1:106415)
    at Or.e.opaquePass (ImageMapper.js:1:106149)
    at Ve.e.apply (ImageMapper.js:1:31795)
    at Ve.e.traverse (ImageMapper.js:1:31654)
    at ImageMapper.js:1:127823
    at Array.forEach (<anonymous>)

### Environment
- **vtk.js**: 26.5.1 
- **OS**: MacOS 12.6.1 
- **Browser**: Chrome 109.0.5414.119 (Official Build) (x86_64); Safari Version 16.1 (17614.2.9.1.13, 17614)

**Comment by floryst** [comment]
@jadh4v this looks like it's coming from #2666.

**Comment by jilei-hao** [comment]
Thanks for the quick fix!
