### ISSUE TITLE
WebGL Crashes on Windows

### ISSUE THREAD

**Issue by agirault** [Kitware/vtk-js#548]
"WebGL hit a snag" error in Chrome on Windows.

* See crash log attached below:
https://github.com/Kitware/vtk-js/files/1679019/1517331927361.log

* It seems to originate from missing gl context in `vtkOpenGLRenderWindow.initialize`: https://github.com/Kitware/vtk-js/blob/v5.15.11/Sources/Rendering/OpenGL/RenderWindow/index.js#L62-L63

* This links gives tips to fix the issue, linked to disabled hardware acceleration or webgl flags: https://wildtricks.com/webgl-hit-a-snag-solved/

* This links shows minimum requirements to use WebGL:
https://www.khronos.org/webgl/wiki/BlacklistsAndWhitelists

Specs:
- CPU - i5-6400 2.7 GHz (Integrated graphics) -> looking for the driver version
 now
- RAM - 8GB
- 64-bit
- No dedicated GPU

**Comment by agirault** [comment]
Other issues happening in the same vein:

Firefox on Windows:
```
TypeError: model.context.getParameter(...) is null
[Learn More]
project.js:69525:15
vtkShaderCache/publicAPI.replaceShaderValues
http://localhost:9990/project.js:69525:15
vtkShaderCache/publicAPI.readyShaderProgramArray
http://localhost:9990/project.js:69553:16
vtkOpenGLVolumeMapper/publicAPI.updateShaders
http://localhost:9990/project.js:68709:23
vtkOpenGLVolumeMapper/publicAPI.renderPieceDraw
http://localhost:9990/project.js:69132:5
vtkOpenGLVolumeMapper/publicAPI.renderPiece
http://localhost:9990/project.js:69209:5
vtkOpenGLVolumeMapper/publicAPI.volumePass
http://localhost:9990/project.js:68510:7
vtkViewNode/publicAPI.apply
http://localhost:9990/project.js:4590:7
vtkViewNode/publicAPI.traverse
http://localhost:9990/project.js:4578:5
vtkOpenGLVolume/publicAPI.traverseVolumePass
http://localhost:9990/project.js:68312:5
vtkViewNode/publicAPI.traverse
http://localhost:9990/project.js:4573:7
vtkViewNode/publicAPI.traverse
http://localhost:9990/project.js:4581:7
vtkForwardPass/publicAPI.traverse
http://localhost:9990/project.js:64438:9
vtkOpenGLRenderWindow/publicAPI.traverseAllPasses
http://localhost:9990/project.js:28855:9
vtkRenderWindowInteractor/publicAPI.forceRender
http://localhost:9990/project.js:23376:7
vtkRenderWindowInteractor/publicAPI.handleAnimation
http://localhost:9990/project.js:23146:5
[object Object] did not request an animation
project.js:174:3

Error: WebGL warning: Failed to create WebGL context: WebGL creation failed: 
* Error during ANGLE OpenGL init.
* Error during ANGLE OpenGL init.
* Error during ANGLE OpenGL init.
* Error during ANGLE OpenGL init.
* Error during ANGLE OpenGL init.
* Exhausted GL driver caps.

TypeError: model.glFramebuffer is null
[Learn More]
project.js:17173:5
vtkFramebuffer/publicAPI.create
http://localhost:9990/project.js:17173:5
vtkForwardPass/publicAPI.traverse
http://localhost:9990/project.js:64417:11
vtkOpenGLRenderWindow/publicAPI.traverseAllPasses
http://localhost:9990/project.js:28855:9
vtkRenderWindowInteractor/publicAPI.forceRender
http://localhost:9990/project.js:23376:7
vtkRenderWindowInteractor/publicAPI.render
http://localhost:9990/project.js:23389:7
vtkOrientationMarkerWidget/publicAPI.updateViewport
http://localhost:9990/project.js:70198:5
obj/publicAPI.modified/<
http://localhost:9990/project.js:256:26
forEach self-hosted:271:13 obj/publicAPI.modified
http://localhost:9990/project.js:255:5
<anonymous>
http://localhost:9990/project.js:580:9
vtkViewProxy/publicAPI.resize
http://localhost:9990/project.js:27738:7
addViewHandlingAPI/publicAPI.resizeAllViews
http://localhost:9990/project.js:62117:7
```

Chrome on Windows:
```
localhost/:1 WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
localhost/:1 WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
localhost/:1 WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
localhost/:1 WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
project.js:69525 Uncaught TypeError: Cannot read property 'indexOf' of null
    at Object.publicAPI.replaceShaderValues (project.js:69525)
    at Object.publicAPI.readyShaderProgramArray (project.js:69553)
    at Object.publicAPI.updateShaders (project.js:68709)
    at Object.publicAPI.renderPieceDraw (project.js:69132)
    at Object.publicAPI.renderPiece (project.js:69209)
    at publicAPI.volumePass (project.js:68510)
    at Object.publicAPI.apply (project.js:4590)
    at Object.publicAPI.traverse (project.js:4578)
    at publicAPI.traverseVolumePass (project.js:68312)
    at Object.publicAPI.traverse (project.js:4573)
    at publicAPI.traverse @ project.js:4581
    at publicAPI.traverse @ project.js:64438
    at publicAPI.traverseAllPasses @ project.js:28855
    at publicAPI.forceRender @ project.js:23376
    at publicAPI.render @ project.js:23389
    at publicAPI.updateViewport @ project.js:70198
    at http://localhost:9990/project.js:256

project.js:17173 Uncaught TypeError: Cannot set property 'width' of null
    at Object.publicAPI.create (http://localhost:9990/project.js:17173:31)
    at Object.publicAPI.traverse (http://localhost:9990/project.js:64417:29)
    at Object.publicAPI.traverseAllPasses (http://localhost:9990/project.js:28855:35)
    at Object.publicAPI.forceRender (http://localhost:9990/project.js:23376:18)
    at Object.publicAPI.render (http://localhost:9990/project.js:23389:17)
    at publicAPI.updateViewport (http://localhost:9990/project.js:70198:22)
    at http://localhost:9990/project.js:256:26
    at Array.forEach (<anonymous>)
    at Object.publicAPI.modified (http://localhost:9990/project.js:255:15)
    at Object.publicAPI.(anonymous function) [as setSize] (http://localhost:9990/project.js:580:19)
```

**Comment by agirault** [comment]
fixed by https://github.com/Kitware/vtk-js/pull/643 and https://github.com/Kitware/vtk-js/pull/638

**Comment by gaston-perret** [comment]
Hello. I'm having errors that I think are realted to this issue in Chrome.
Firefox runs perfectly.
I'm using VTK JS version 14.16.2

The error I get is "Uncaught TypeError: Cannot set property 'width' of null"

**Comment by gaston-perret** [comment]
> Hello. I'm having errors that I think are realted to this issue in Chrome.
> Firefox runs perfectly.
> I'm using VTK JS version 14.16.2
> 
> The error I get is "Uncaught TypeError: Cannot set property 'width' of null"

Hi @jourdain do you have any info about this? Thanks.

**Comment by jourdain** [comment]
Please create a new issue with the proper information on how to reproduce. Maybe a code pen example?
