### ISSUE TITLE
doc:www rule fails on windows

### ISSUE THREAD

**Issue by martinken** [Kitware/vtk-js#849]
[WEBPACK] Started building VolumeViewer.js
Unhandled rejection WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[0].test: The provided value "C:UserskennyDocuments\u000btk-js\u000btk-jsExamplesApplicationsSkyboxViewerindex.js" is not an absolute path!
   -> A rule
 - configuration.output.path: The provided value "C:UserskennyDocuments\u000btk-js\u000btk-jsDocumentation\build-tmppublicexamplesSkyboxViewer" is not an absolute path!
   -> The output directory as **absolute path** (required).
    at webpack (C:\Users\kenny\Documents\vtk-js\vtk-js\node_modules\webpack\lib\webpack.js:24:9)
    at C:\Users\kenny\Documents\vtk-js\vtk-js\node_modules\parallel-webpack\src\webpackWorker.js:146:24
    at tryCatcher (C:\Users\kenny\Documents\vtk-js\vtk-js\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\kenny\Documents\vtk-js\vtk-js\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\kenny\Documents\vtk-js\vtk-js\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromiseCtx (C:\Users\kenny\Documents\vtk-js\vtk-js\node_modules\bluebird\js\release\promise.js:606:10)

**Comment by jourdain** [comment]
Windows again... ;-)

**Comment by jourdain** [comment]
I guess the change I made to parallel build the examples didn't help...

**Comment by mix3d** [comment]
this is still an issue for me as well. I'm fortunate that I recently bought a mac but I'm working on both a windows and a mac simultaneously.

**Comment by floryst** [comment]
@martinken assigning you for update on if this is still an issue.
