### ISSUE TITLE
React with vtkjs

### ISSUE THREAD

**Issue by jackyko1991** [Kitware/vtk-js#899]
I am trying to integrate reactjs with vtk js to build my own web app. Both examples works well in [ES6 build](https://kitware.github.io/vtk-js/docs/intro_vtk_as_es6_dependency.html) and [React Webpack Build](https://medium.com/@jishnu61/react-16-webpack-4-react-router-babel-6-material-ui-2018-10682441ad1e)

Problem comes in when two thing integrates together. I have also read the issues [here](https://stackoverflow.com/questions/48907794/vtk-js-react-javascript-load-vtk-files) and https://github.com/Kitware/vtk-js/issues/785.

Can anyone give a help on writing `webpack.config`?

```javascript
const webpack = require('webpack');
var path = require('path');
var vtkRules = require('vtk.js/Utilities/config/dependency.js').webpack.v2.rules

var entry = path.join(__dirname, './src/index.js');
const sourcePath = path.join(__dirname, './src');

module.exports = {
  entry: './src/index.js',
  module: {
  	rules:[
  	{
  		test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        loader: ["expose-loader?bundle",'babel-loader'] //vtk use expose loader on local node_modules while babel seems cannot load the local one, this code works fine with react but not with vtkjs
  	},
  	{
  		test: /\.html$/, 
  		loader: 'html-loader' 
  	},
  	].concat(vtkRules),
  },
  resolve: {
  	modules: [
      path.resolve(__dirname, 'node_modules'),
      sourcePath,
    ],
    extensions: ['*', '.js', '.jsx']
  },
  output: {
    path: __dirname + '/dist',
    publicPath: '/',
    filename: 'bundle.js'
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
  ],
  devServer: {
    contentBase: './dist',
    hot: true,
    historyApiFallback: true // this prevents the default browser full page refresh on form submission and link change
  }
};
```
error message:
```
ERROR in ./node_modules/vtk.js/Sources/Rendering/Misc/FullScreenRenderWindow/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\scope\index.js:867:13)
    at BlockScoping.updateScopeInfo (D:\Projects\react_vtk_2\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:364:17)
    at BlockScoping.run (D:\Projects\react_vtk_2\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:330:12)
    at PluginPass.BlockStatementSwitchStatementProgram (D:\Projects\react_vtk_2\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:70:24)
    at newFn (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\visitors.js:193:21)
    at NodePath._call (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitSingle (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:90:19)
    at TraversalContext.visit (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:146:19)
    at Function.traverse.node (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:94:17)
    at traverse (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:76:12)
    at transformFile (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transformation\index.js:88:29)
    at runSync (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transformation\index.js:45:3)
    at runAsync (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transformation\index.js:35:14)
    at process.nextTick (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transform.js:34:34)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
 @ ./src/index.js 1:0-93 16:27-52
 @ ./src/index.js-exposed

ERROR in ./node_modules/vtk.js/Sources/Rendering/Core/Actor/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\scope\index.js:867:13)
    at BlockScoping.updateScopeInfo (D:\Projects\react_vtk_2\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:364:17)
    at BlockScoping.run (D:\Projects\react_vtk_2\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:330:12)
    at PluginPass.BlockStatementSwitchStatementProgram (D:\Projects\react_vtk_2\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:70:24)
    at newFn (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\visitors.js:193:21)
    at NodePath._call (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitSingle (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:90:19)
    at TraversalContext.visit (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:146:19)
    at Function.traverse.node (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:94:17)
    at traverse (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:76:12)
    at transformFile (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transformation\index.js:88:29)
    at runSync (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transformation\index.js:45:3)
    at runAsync (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transformation\index.js:35:14)
    at process.nextTick (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transform.js:34:34)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
 @ ./src/index.js 3:0-69 46:14-22
 @ ./src/index.js-exposed

ERROR in ./node_modules/vtk.js/Sources/Filters/General/Calculator/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\scope\index.js:867:13)
    at BlockScoping.updateScopeInfo (D:\Projects\react_vtk_2\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:364:17)
    at BlockScoping.run (D:\Projects\react_vtk_2\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:330:12)
    at PluginPass.BlockStatementSwitchStatementProgram (D:\Projects\react_vtk_2\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:70:24)
    at newFn (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\visitors.js:193:21)
    at NodePath._call (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitSingle (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:90:19)
    at TraversalContext.visit (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:146:19)
    at Function.traverse.node (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:94:17)
    at traverse (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:76:12)
    at transformFile (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transformation\index.js:88:29)
    at runSync (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transformation\index.js:45:3)
    at runAsync (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transformation\index.js:35:14)
    at process.nextTick (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transform.js:34:34)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
 @ ./src/index.js 4:0-75 25:15-28
 @ ./src/index.js-exposed

ERROR in ./node_modules/vtk.js/Sources/Rendering/Core/Mapper/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\scope\index.js:867:13)
    at BlockScoping.updateScopeInfo (D:\Projects\react_vtk_2\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:364:17)
    at BlockScoping.run (D:\Projects\react_vtk_2\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:330:12)
    at PluginPass.BlockStatementSwitchStatementProgram (D:\Projects\react_vtk_2\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:70:24)
    at newFn (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\visitors.js:193:21)
    at NodePath._call (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitSingle (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:90:19)
    at TraversalContext.visit (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:146:19)
    at Function.traverse.node (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:94:17)
    at traverse (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:76:12)
    at transformFile (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transformation\index.js:88:29)
    at runSync (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transformation\index.js:45:3)
    at runAsync (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transformation\index.js:35:14)
    at process.nextTick (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transform.js:34:34)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
 @ ./src/index.js 6:0-70 43:15-24
 @ ./src/index.js-exposed

ERROR in ./node_modules/vtk.js/Sources/Filters/Sources/ConeSource/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\scope\index.js:867:13)
    at BlockScoping.updateScopeInfo (D:\Projects\react_vtk_2\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:364:17)
    at BlockScoping.run (D:\Projects\react_vtk_2\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:330:12)
    at PluginPass.BlockStatementSwitchStatementProgram (D:\Projects\react_vtk_2\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:70:24)
    at newFn (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\visitors.js:193:21)
    at NodePath._call (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitSingle (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:90:19)
    at TraversalContext.visit (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:146:19)
    at Function.traverse.node (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:94:17)
    at traverse (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:76:12)
    at transformFile (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transformation\index.js:88:29)
    at runSync (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transformation\index.js:45:3)
    at runAsync (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transformation\index.js:35:14)
    at process.nextTick (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transform.js:34:34)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
 @ ./src/index.js 5:0-75 24:19-32
 @ ./src/index.js-exposed

ERROR in ./node_modules/vtk.js/Sources/Common/DataModel/DataSetAttributes/Constants.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\scope\index.js:867:13)
    at convertBlockScopedToVar (D:\Projects\react_vtk_2\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:139:13)
    at PluginPass.VariableDeclaration (D:\Projects\react_vtk_2\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:26:9)
    at newFn (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\visitors.js:193:21)
    at NodePath._call (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitSingle (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:90:19)
    at TraversalContext.visit (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:146:19)
    at Function.traverse.node (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:94:17)
    at NodePath.visit (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:95:18)
    at TraversalContext.visitQueue (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitMultiple (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:85:17)
    at TraversalContext.visit (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:144:19)
    at Function.traverse.node (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:94:17)
    at NodePath.visit (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:95:18)
    at TraversalContext.visitQueue (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitSingle (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:90:19)
    at TraversalContext.visit (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:146:19)
    at Function.traverse.node (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:94:17)
    at traverse (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:76:12)
    at transformFile (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transformation\index.js:88:29)
    at runSync (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transformation\index.js:45:3)
    at runAsync (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transformation\index.js:35:14)
    at process.nextTick (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transform.js:34:34)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
 @ ./src/index.js 7:0-93 32:92-106
 @ ./src/index.js-exposed

ERROR in ./node_modules/vtk.js/Sources/Common/DataModel/DataSet/Constants.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\scope\index.js:867:13)
    at convertBlockScopedToVar (D:\Projects\react_vtk_2\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:139:13)
    at PluginPass.VariableDeclaration (D:\Projects\react_vtk_2\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:26:9)
    at newFn (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\visitors.js:193:21)
    at NodePath._call (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitSingle (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:90:19)
    at TraversalContext.visit (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:146:19)
    at Function.traverse.node (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:94:17)
    at NodePath.visit (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:95:18)
    at TraversalContext.visitQueue (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitMultiple (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:85:17)
    at TraversalContext.visit (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:144:19)
    at Function.traverse.node (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:94:17)
    at NodePath.visit (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:95:18)
    at TraversalContext.visitQueue (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitSingle (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:90:19)
    at TraversalContext.visit (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:146:19)
    at Function.traverse.node (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:94:17)
    at traverse (D:\Projects\react_vtk_2\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:76:12)
    at transformFile (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transformation\index.js:88:29)
    at runSync (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transformation\index.js:45:3)
    at runAsync (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transformation\index.js:35:14)
    at process.nextTick (D:\Projects\react_vtk_2\node_modules\@babel\core\lib\transform.js:34:34)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
 @ ./src/index.js 8:0-83 32:18-32
 @ ./src/index.js-exposed
```

**Comment by jackyko1991** [comment]
I have try to modified to 

```Javascript
var path = require('path');
var webpack = require('webpack');
var vtkRules = require('vtk.js/Utilities/config/dependency.js').webpack.v2.rules;

var entry = path.join(__dirname, './src/index.js');
const sourcePath = path.join(__dirname, './src');
const outputPath = path.join(__dirname, './dist');

module.exports = {
  entry,
  output: {
    path: outputPath,
    filename: 'bundle.js',
  },
  module: {
    rules: [
        {
            test: /\.js$/,
            exclude: /node_modules/,
            use: {
              loader: "babel-loader"
            }
        },
        { test: entry, loader: "expose-loader?bundle" },
        { test: /\.html$/, loader: 'html-loader' },
    ].concat(vtkRules),
  },
  resolve: {
    modules: [
      path.resolve(__dirname, 'node_modules'),
      sourcePath,
    ],
  },
};
```

same error occurs

**Comment by jourdain** [comment]
Do you have a file at `./src/index.js` ?

**Comment by jourdain** [comment]
Do you need the expose loader?

**Comment by jourdain** [comment]
Is that related to https://github.com/babel/babel/issues/6186

**Comment by jourdain** [comment]
Thanks for the update. I don't have a timeframe but we will update our toolchain soon enough to get the latest babel and so on. Once we do that, you'll have the freedom to use todays versions. ;-)
